# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DEPLOY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: SSH Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/marvelapi.iondrimbafilho.me/public_html && git pull
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: root
          privateKey: ${{ secrets.SSH_DIGITAL_OCEAN}}
